/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FeeCollectorV2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "BURN_PERCENT"
      | "REFERRAL_PERCENT"
      | "TREASURY_PERCENT"
      | "convertTokenToBnb"
      | "dexRouter"
      | "distributeFees"
      | "emergencyWithdraw"
      | "minDistributionAmount"
      | "owner"
      | "pause"
      | "paused"
      | "pilotToken"
      | "referralPool"
      | "renounceOwnership"
      | "setDexRouter"
      | "setMinDistributionAmount"
      | "setReferralPool"
      | "setTreasury"
      | "totalFeesCollected"
      | "totalPilotBurned"
      | "transferOwnership"
      | "treasury"
      | "unpause"
      | "wbnb"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DexRouterUpdated"
      | "FeesCollected"
      | "FeesDistributed"
      | "MinDistributionAmountUpdated"
      | "OwnershipTransferred"
      | "Paused"
      | "PilotBurned"
      | "ReferralPoolUpdated"
      | "TreasuryUpdated"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BURN_PERCENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REFERRAL_PERCENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TREASURY_PERCENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "convertTokenToBnb",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "dexRouter", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "distributeFees",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "minDistributionAmount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pilotToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "referralPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDexRouter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinDistributionAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setReferralPool",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalFeesCollected",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalPilotBurned",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(functionFragment: "wbnb", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "BURN_PERCENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REFERRAL_PERCENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TREASURY_PERCENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "convertTokenToBnb",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "dexRouter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "distributeFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minDistributionAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pilotToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "referralPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDexRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinDistributionAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReferralPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalFeesCollected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalPilotBurned",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "wbnb", data: BytesLike): Result;
}

export namespace DexRouterUpdatedEvent {
  export type InputTuple = [oldRouter: AddressLike, newRouter: AddressLike];
  export type OutputTuple = [oldRouter: string, newRouter: string];
  export interface OutputObject {
    oldRouter: string;
    newRouter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeesCollectedEvent {
  export type InputTuple = [token: AddressLike, amount: BigNumberish];
  export type OutputTuple = [token: string, amount: bigint];
  export interface OutputObject {
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeesDistributedEvent {
  export type InputTuple = [
    burnAmount: BigNumberish,
    treasuryAmount: BigNumberish,
    referralAmount: BigNumberish
  ];
  export type OutputTuple = [
    burnAmount: bigint,
    treasuryAmount: bigint,
    referralAmount: bigint
  ];
  export interface OutputObject {
    burnAmount: bigint;
    treasuryAmount: bigint;
    referralAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinDistributionAmountUpdatedEvent {
  export type InputTuple = [oldAmount: BigNumberish, newAmount: BigNumberish];
  export type OutputTuple = [oldAmount: bigint, newAmount: bigint];
  export interface OutputObject {
    oldAmount: bigint;
    newAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PilotBurnedEvent {
  export type InputTuple = [bnbSpent: BigNumberish, pilotBurned: BigNumberish];
  export type OutputTuple = [bnbSpent: bigint, pilotBurned: bigint];
  export interface OutputObject {
    bnbSpent: bigint;
    pilotBurned: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReferralPoolUpdatedEvent {
  export type InputTuple = [oldPool: AddressLike, newPool: AddressLike];
  export type OutputTuple = [oldPool: string, newPool: string];
  export interface OutputObject {
    oldPool: string;
    newPool: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryUpdatedEvent {
  export type InputTuple = [oldTreasury: AddressLike, newTreasury: AddressLike];
  export type OutputTuple = [oldTreasury: string, newTreasury: string];
  export interface OutputObject {
    oldTreasury: string;
    newTreasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FeeCollectorV2 extends BaseContract {
  connect(runner?: ContractRunner | null): FeeCollectorV2;
  waitForDeployment(): Promise<this>;

  interface: FeeCollectorV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BURN_PERCENT: TypedContractMethod<[], [bigint], "view">;

  REFERRAL_PERCENT: TypedContractMethod<[], [bigint], "view">;

  TREASURY_PERCENT: TypedContractMethod<[], [bigint], "view">;

  convertTokenToBnb: TypedContractMethod<
    [token: AddressLike, minBnbOut: BigNumberish],
    [void],
    "nonpayable"
  >;

  dexRouter: TypedContractMethod<[], [string], "view">;

  distributeFees: TypedContractMethod<
    [minPilotOut: BigNumberish],
    [void],
    "nonpayable"
  >;

  emergencyWithdraw: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  minDistributionAmount: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pilotToken: TypedContractMethod<[], [string], "view">;

  referralPool: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setDexRouter: TypedContractMethod<
    [_dexRouter: AddressLike],
    [void],
    "nonpayable"
  >;

  setMinDistributionAmount: TypedContractMethod<
    [_minAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setReferralPool: TypedContractMethod<
    [_referralPool: AddressLike],
    [void],
    "nonpayable"
  >;

  setTreasury: TypedContractMethod<
    [_treasury: AddressLike],
    [void],
    "nonpayable"
  >;

  totalFeesCollected: TypedContractMethod<[], [bigint], "view">;

  totalPilotBurned: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  wbnb: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BURN_PERCENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REFERRAL_PERCENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TREASURY_PERCENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "convertTokenToBnb"
  ): TypedContractMethod<
    [token: AddressLike, minBnbOut: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "dexRouter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "distributeFees"
  ): TypedContractMethod<[minPilotOut: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "minDistributionAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pilotToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "referralPool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDexRouter"
  ): TypedContractMethod<[_dexRouter: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMinDistributionAmount"
  ): TypedContractMethod<[_minAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setReferralPool"
  ): TypedContractMethod<[_referralPool: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[_treasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalFeesCollected"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalPilotBurned"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "wbnb"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "DexRouterUpdated"
  ): TypedContractEvent<
    DexRouterUpdatedEvent.InputTuple,
    DexRouterUpdatedEvent.OutputTuple,
    DexRouterUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FeesCollected"
  ): TypedContractEvent<
    FeesCollectedEvent.InputTuple,
    FeesCollectedEvent.OutputTuple,
    FeesCollectedEvent.OutputObject
  >;
  getEvent(
    key: "FeesDistributed"
  ): TypedContractEvent<
    FeesDistributedEvent.InputTuple,
    FeesDistributedEvent.OutputTuple,
    FeesDistributedEvent.OutputObject
  >;
  getEvent(
    key: "MinDistributionAmountUpdated"
  ): TypedContractEvent<
    MinDistributionAmountUpdatedEvent.InputTuple,
    MinDistributionAmountUpdatedEvent.OutputTuple,
    MinDistributionAmountUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PilotBurned"
  ): TypedContractEvent<
    PilotBurnedEvent.InputTuple,
    PilotBurnedEvent.OutputTuple,
    PilotBurnedEvent.OutputObject
  >;
  getEvent(
    key: "ReferralPoolUpdated"
  ): TypedContractEvent<
    ReferralPoolUpdatedEvent.InputTuple,
    ReferralPoolUpdatedEvent.OutputTuple,
    ReferralPoolUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryUpdated"
  ): TypedContractEvent<
    TreasuryUpdatedEvent.InputTuple,
    TreasuryUpdatedEvent.OutputTuple,
    TreasuryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "DexRouterUpdated(address,address)": TypedContractEvent<
      DexRouterUpdatedEvent.InputTuple,
      DexRouterUpdatedEvent.OutputTuple,
      DexRouterUpdatedEvent.OutputObject
    >;
    DexRouterUpdated: TypedContractEvent<
      DexRouterUpdatedEvent.InputTuple,
      DexRouterUpdatedEvent.OutputTuple,
      DexRouterUpdatedEvent.OutputObject
    >;

    "FeesCollected(address,uint256)": TypedContractEvent<
      FeesCollectedEvent.InputTuple,
      FeesCollectedEvent.OutputTuple,
      FeesCollectedEvent.OutputObject
    >;
    FeesCollected: TypedContractEvent<
      FeesCollectedEvent.InputTuple,
      FeesCollectedEvent.OutputTuple,
      FeesCollectedEvent.OutputObject
    >;

    "FeesDistributed(uint256,uint256,uint256)": TypedContractEvent<
      FeesDistributedEvent.InputTuple,
      FeesDistributedEvent.OutputTuple,
      FeesDistributedEvent.OutputObject
    >;
    FeesDistributed: TypedContractEvent<
      FeesDistributedEvent.InputTuple,
      FeesDistributedEvent.OutputTuple,
      FeesDistributedEvent.OutputObject
    >;

    "MinDistributionAmountUpdated(uint256,uint256)": TypedContractEvent<
      MinDistributionAmountUpdatedEvent.InputTuple,
      MinDistributionAmountUpdatedEvent.OutputTuple,
      MinDistributionAmountUpdatedEvent.OutputObject
    >;
    MinDistributionAmountUpdated: TypedContractEvent<
      MinDistributionAmountUpdatedEvent.InputTuple,
      MinDistributionAmountUpdatedEvent.OutputTuple,
      MinDistributionAmountUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PilotBurned(uint256,uint256)": TypedContractEvent<
      PilotBurnedEvent.InputTuple,
      PilotBurnedEvent.OutputTuple,
      PilotBurnedEvent.OutputObject
    >;
    PilotBurned: TypedContractEvent<
      PilotBurnedEvent.InputTuple,
      PilotBurnedEvent.OutputTuple,
      PilotBurnedEvent.OutputObject
    >;

    "ReferralPoolUpdated(address,address)": TypedContractEvent<
      ReferralPoolUpdatedEvent.InputTuple,
      ReferralPoolUpdatedEvent.OutputTuple,
      ReferralPoolUpdatedEvent.OutputObject
    >;
    ReferralPoolUpdated: TypedContractEvent<
      ReferralPoolUpdatedEvent.InputTuple,
      ReferralPoolUpdatedEvent.OutputTuple,
      ReferralPoolUpdatedEvent.OutputObject
    >;

    "TreasuryUpdated(address,address)": TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;
    TreasuryUpdated: TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
