/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as feeCollectorSol from "./FeeCollector.sol";
export type { feeCollectorSol };
export type { PILOTToken } from "./PILOTToken";
