/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ReferralRewardsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "REFERRAL_ALLOCATION"
      | "accrueReward"
      | "claimRewards"
      | "codeToReferrer"
      | "distributors"
      | "emergencyWithdraw"
      | "getReferrerFromCode"
      | "getReferrerStats"
      | "getRemainingAllocation"
      | "isCodeAvailable"
      | "linkUserToReferrer"
      | "maxRewardPerSwap"
      | "minSwapVolumeUsd"
      | "owner"
      | "pause"
      | "paused"
      | "pendingRewards"
      | "pilotToken"
      | "referralCount"
      | "referredVolume"
      | "referrerCodes"
      | "registerReferralCode"
      | "renounceOwnership"
      | "rewardRatePerDollar"
      | "setDistributor"
      | "setMaxRewardPerSwap"
      | "setMinSwapVolume"
      | "setRewardRate"
      | "totalEarned"
      | "totalRewardsDistributed"
      | "transferOwnership"
      | "unpause"
      | "userReferrer"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DistributorUpdated"
      | "EmergencyWithdraw"
      | "MaxRewardPerSwapUpdated"
      | "MinSwapVolumeUpdated"
      | "OwnershipTransferred"
      | "Paused"
      | "ReferralCodeCreated"
      | "RewardAccrued"
      | "RewardRateUpdated"
      | "RewardsClaimed"
      | "Unpaused"
      | "UserReferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "REFERRAL_ALLOCATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "accrueReward",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRewards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "codeToReferrer",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "distributors",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReferrerFromCode",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getReferrerStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRemainingAllocation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isCodeAvailable",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "linkUserToReferrer",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "maxRewardPerSwap",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minSwapVolumeUsd",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingRewards",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pilotToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "referralCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "referredVolume",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "referrerCodes",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerReferralCode",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewardRatePerDollar",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDistributor",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxRewardPerSwap",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinSwapVolume",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setRewardRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalEarned",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalRewardsDistributed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userReferrer",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "REFERRAL_ALLOCATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "accrueReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "codeToReferrer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReferrerFromCode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReferrerStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRemainingAllocation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isCodeAvailable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "linkUserToReferrer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxRewardPerSwap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minSwapVolumeUsd",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pilotToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "referralCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "referredVolume",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "referrerCodes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerReferralCode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardRatePerDollar",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxRewardPerSwap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinSwapVolume",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRewardRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalEarned",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalRewardsDistributed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userReferrer",
    data: BytesLike
  ): Result;
}

export namespace DistributorUpdatedEvent {
  export type InputTuple = [distributor: AddressLike, authorized: boolean];
  export type OutputTuple = [distributor: string, authorized: boolean];
  export interface OutputObject {
    distributor: string;
    authorized: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyWithdrawEvent {
  export type InputTuple = [
    token: AddressLike,
    amount: BigNumberish,
    to: AddressLike
  ];
  export type OutputTuple = [token: string, amount: bigint, to: string];
  export interface OutputObject {
    token: string;
    amount: bigint;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaxRewardPerSwapUpdatedEvent {
  export type InputTuple = [oldMax: BigNumberish, newMax: BigNumberish];
  export type OutputTuple = [oldMax: bigint, newMax: bigint];
  export interface OutputObject {
    oldMax: bigint;
    newMax: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinSwapVolumeUpdatedEvent {
  export type InputTuple = [oldMin: BigNumberish, newMin: BigNumberish];
  export type OutputTuple = [oldMin: bigint, newMin: bigint];
  export interface OutputObject {
    oldMin: bigint;
    newMin: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReferralCodeCreatedEvent {
  export type InputTuple = [referrer: AddressLike, codeHash: BytesLike];
  export type OutputTuple = [referrer: string, codeHash: string];
  export interface OutputObject {
    referrer: string;
    codeHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardAccruedEvent {
  export type InputTuple = [
    referrer: AddressLike,
    user: AddressLike,
    swapVolumeUsd: BigNumberish,
    rewardAmount: BigNumberish
  ];
  export type OutputTuple = [
    referrer: string,
    user: string,
    swapVolumeUsd: bigint,
    rewardAmount: bigint
  ];
  export interface OutputObject {
    referrer: string;
    user: string;
    swapVolumeUsd: bigint;
    rewardAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardRateUpdatedEvent {
  export type InputTuple = [oldRate: BigNumberish, newRate: BigNumberish];
  export type OutputTuple = [oldRate: bigint, newRate: bigint];
  export interface OutputObject {
    oldRate: bigint;
    newRate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsClaimedEvent {
  export type InputTuple = [referrer: AddressLike, amount: BigNumberish];
  export type OutputTuple = [referrer: string, amount: bigint];
  export interface OutputObject {
    referrer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserReferredEvent {
  export type InputTuple = [user: AddressLike, referrer: AddressLike];
  export type OutputTuple = [user: string, referrer: string];
  export interface OutputObject {
    user: string;
    referrer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReferralRewards extends BaseContract {
  connect(runner?: ContractRunner | null): ReferralRewards;
  waitForDeployment(): Promise<this>;

  interface: ReferralRewardsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  REFERRAL_ALLOCATION: TypedContractMethod<[], [bigint], "view">;

  accrueReward: TypedContractMethod<
    [user: AddressLike, swapVolumeUsd: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimRewards: TypedContractMethod<[], [void], "nonpayable">;

  codeToReferrer: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  distributors: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  emergencyWithdraw: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getReferrerFromCode: TypedContractMethod<[code: string], [string], "view">;

  getReferrerStats: TypedContractMethod<
    [referrer: AddressLike],
    [
      [bigint, bigint, bigint, bigint, string] & {
        pending: bigint;
        totalEarnedAmount: bigint;
        volumeReferred: bigint;
        usersReferred: bigint;
        codeHash: string;
      }
    ],
    "view"
  >;

  getRemainingAllocation: TypedContractMethod<[], [bigint], "view">;

  isCodeAvailable: TypedContractMethod<[code: string], [boolean], "view">;

  linkUserToReferrer: TypedContractMethod<
    [user: AddressLike, code: string],
    [void],
    "nonpayable"
  >;

  maxRewardPerSwap: TypedContractMethod<[], [bigint], "view">;

  minSwapVolumeUsd: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pendingRewards: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  pilotToken: TypedContractMethod<[], [string], "view">;

  referralCount: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  referredVolume: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  referrerCodes: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  registerReferralCode: TypedContractMethod<
    [code: string],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  rewardRatePerDollar: TypedContractMethod<[], [bigint], "view">;

  setDistributor: TypedContractMethod<
    [distributor: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;

  setMaxRewardPerSwap: TypedContractMethod<
    [maxReward: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMinSwapVolume: TypedContractMethod<
    [minVolumeUsd: BigNumberish],
    [void],
    "nonpayable"
  >;

  setRewardRate: TypedContractMethod<
    [newRatePerDollar: BigNumberish],
    [void],
    "nonpayable"
  >;

  totalEarned: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  totalRewardsDistributed: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  userReferrer: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "REFERRAL_ALLOCATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "accrueReward"
  ): TypedContractMethod<
    [user: AddressLike, swapVolumeUsd: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimRewards"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "codeToReferrer"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "distributors"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getReferrerFromCode"
  ): TypedContractMethod<[code: string], [string], "view">;
  getFunction(
    nameOrSignature: "getReferrerStats"
  ): TypedContractMethod<
    [referrer: AddressLike],
    [
      [bigint, bigint, bigint, bigint, string] & {
        pending: bigint;
        totalEarnedAmount: bigint;
        volumeReferred: bigint;
        usersReferred: bigint;
        codeHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRemainingAllocation"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isCodeAvailable"
  ): TypedContractMethod<[code: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "linkUserToReferrer"
  ): TypedContractMethod<
    [user: AddressLike, code: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "maxRewardPerSwap"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minSwapVolumeUsd"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingRewards"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "pilotToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "referralCount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "referredVolume"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "referrerCodes"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "registerReferralCode"
  ): TypedContractMethod<[code: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rewardRatePerDollar"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setDistributor"
  ): TypedContractMethod<
    [distributor: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMaxRewardPerSwap"
  ): TypedContractMethod<[maxReward: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMinSwapVolume"
  ): TypedContractMethod<[minVolumeUsd: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRewardRate"
  ): TypedContractMethod<
    [newRatePerDollar: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalEarned"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalRewardsDistributed"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userReferrer"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getEvent(
    key: "DistributorUpdated"
  ): TypedContractEvent<
    DistributorUpdatedEvent.InputTuple,
    DistributorUpdatedEvent.OutputTuple,
    DistributorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyWithdraw"
  ): TypedContractEvent<
    EmergencyWithdrawEvent.InputTuple,
    EmergencyWithdrawEvent.OutputTuple,
    EmergencyWithdrawEvent.OutputObject
  >;
  getEvent(
    key: "MaxRewardPerSwapUpdated"
  ): TypedContractEvent<
    MaxRewardPerSwapUpdatedEvent.InputTuple,
    MaxRewardPerSwapUpdatedEvent.OutputTuple,
    MaxRewardPerSwapUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MinSwapVolumeUpdated"
  ): TypedContractEvent<
    MinSwapVolumeUpdatedEvent.InputTuple,
    MinSwapVolumeUpdatedEvent.OutputTuple,
    MinSwapVolumeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "ReferralCodeCreated"
  ): TypedContractEvent<
    ReferralCodeCreatedEvent.InputTuple,
    ReferralCodeCreatedEvent.OutputTuple,
    ReferralCodeCreatedEvent.OutputObject
  >;
  getEvent(
    key: "RewardAccrued"
  ): TypedContractEvent<
    RewardAccruedEvent.InputTuple,
    RewardAccruedEvent.OutputTuple,
    RewardAccruedEvent.OutputObject
  >;
  getEvent(
    key: "RewardRateUpdated"
  ): TypedContractEvent<
    RewardRateUpdatedEvent.InputTuple,
    RewardRateUpdatedEvent.OutputTuple,
    RewardRateUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RewardsClaimed"
  ): TypedContractEvent<
    RewardsClaimedEvent.InputTuple,
    RewardsClaimedEvent.OutputTuple,
    RewardsClaimedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "UserReferred"
  ): TypedContractEvent<
    UserReferredEvent.InputTuple,
    UserReferredEvent.OutputTuple,
    UserReferredEvent.OutputObject
  >;

  filters: {
    "DistributorUpdated(address,bool)": TypedContractEvent<
      DistributorUpdatedEvent.InputTuple,
      DistributorUpdatedEvent.OutputTuple,
      DistributorUpdatedEvent.OutputObject
    >;
    DistributorUpdated: TypedContractEvent<
      DistributorUpdatedEvent.InputTuple,
      DistributorUpdatedEvent.OutputTuple,
      DistributorUpdatedEvent.OutputObject
    >;

    "EmergencyWithdraw(address,uint256,address)": TypedContractEvent<
      EmergencyWithdrawEvent.InputTuple,
      EmergencyWithdrawEvent.OutputTuple,
      EmergencyWithdrawEvent.OutputObject
    >;
    EmergencyWithdraw: TypedContractEvent<
      EmergencyWithdrawEvent.InputTuple,
      EmergencyWithdrawEvent.OutputTuple,
      EmergencyWithdrawEvent.OutputObject
    >;

    "MaxRewardPerSwapUpdated(uint256,uint256)": TypedContractEvent<
      MaxRewardPerSwapUpdatedEvent.InputTuple,
      MaxRewardPerSwapUpdatedEvent.OutputTuple,
      MaxRewardPerSwapUpdatedEvent.OutputObject
    >;
    MaxRewardPerSwapUpdated: TypedContractEvent<
      MaxRewardPerSwapUpdatedEvent.InputTuple,
      MaxRewardPerSwapUpdatedEvent.OutputTuple,
      MaxRewardPerSwapUpdatedEvent.OutputObject
    >;

    "MinSwapVolumeUpdated(uint256,uint256)": TypedContractEvent<
      MinSwapVolumeUpdatedEvent.InputTuple,
      MinSwapVolumeUpdatedEvent.OutputTuple,
      MinSwapVolumeUpdatedEvent.OutputObject
    >;
    MinSwapVolumeUpdated: TypedContractEvent<
      MinSwapVolumeUpdatedEvent.InputTuple,
      MinSwapVolumeUpdatedEvent.OutputTuple,
      MinSwapVolumeUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "ReferralCodeCreated(address,bytes32)": TypedContractEvent<
      ReferralCodeCreatedEvent.InputTuple,
      ReferralCodeCreatedEvent.OutputTuple,
      ReferralCodeCreatedEvent.OutputObject
    >;
    ReferralCodeCreated: TypedContractEvent<
      ReferralCodeCreatedEvent.InputTuple,
      ReferralCodeCreatedEvent.OutputTuple,
      ReferralCodeCreatedEvent.OutputObject
    >;

    "RewardAccrued(address,address,uint256,uint256)": TypedContractEvent<
      RewardAccruedEvent.InputTuple,
      RewardAccruedEvent.OutputTuple,
      RewardAccruedEvent.OutputObject
    >;
    RewardAccrued: TypedContractEvent<
      RewardAccruedEvent.InputTuple,
      RewardAccruedEvent.OutputTuple,
      RewardAccruedEvent.OutputObject
    >;

    "RewardRateUpdated(uint256,uint256)": TypedContractEvent<
      RewardRateUpdatedEvent.InputTuple,
      RewardRateUpdatedEvent.OutputTuple,
      RewardRateUpdatedEvent.OutputObject
    >;
    RewardRateUpdated: TypedContractEvent<
      RewardRateUpdatedEvent.InputTuple,
      RewardRateUpdatedEvent.OutputTuple,
      RewardRateUpdatedEvent.OutputObject
    >;

    "RewardsClaimed(address,uint256)": TypedContractEvent<
      RewardsClaimedEvent.InputTuple,
      RewardsClaimedEvent.OutputTuple,
      RewardsClaimedEvent.OutputObject
    >;
    RewardsClaimed: TypedContractEvent<
      RewardsClaimedEvent.InputTuple,
      RewardsClaimedEvent.OutputTuple,
      RewardsClaimedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "UserReferred(address,address)": TypedContractEvent<
      UserReferredEvent.InputTuple,
      UserReferredEvent.OutputTuple,
      UserReferredEvent.OutputObject
    >;
    UserReferred: TypedContractEvent<
      UserReferredEvent.InputTuple,
      UserReferredEvent.OutputTuple,
      UserReferredEvent.OutputObject
    >;
  };
}
